# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CheapHerder', '0004_auto_20171105_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CheapHerder.Supplier'),
        ),
    ]
