# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheapHerder', '0013_auto_20171114_2148'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product_price',
            unique_together=set([('price_id', 'item_code')]),
        ),
    ]
