# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CheapHerder', '0015_group_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='transaction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CheapHerder.Transaction'),
        ),
    ]
