# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CheapHerder', '0019_group_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='product_price',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CheapHerder.Product_Price'),
        ),
    ]
