# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheapHerder', '0021_auto_20171204_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGroupPledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('amount_pledged', models.DecimalField(decimal_places=5, max_digits=10)),
                ('time_pledged', models.DateTimeField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
