# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheapHerder', '0022_paymentgrouppledge'),
    ]

    operations = [
	migrations.RunSQL(
	"""CREATE INDEX search ON "CheapHerder_search_item" (keyword)"""
	)
    ]
