# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheapHerder', '0028_create_custom_view'),
    ]

    operations = [
	migrations.RunSQL("""
CREATE OR REPLACE FUNCTION query_product(query_string varchar(255)) RETURNS TABLE (
item_code varchar(255),
product_name varchar(255),
description text,
quantity varchar(255),
package_size varchar(255),
gross_weight varchar(255),
category varchar(255),
image_url varchar(200)
)
AS $$
BEGIN
RETURN QUERY SELECT DISTINCT "CheapHerder_product".item_code,"CheapHerder_product".product_name,"CheapHerder_product".description,"CheapHerder_product".quantity,"CheapHerder_product".package_size,"CheapHerder_product".gross_weight,"CheapHerder_product".category,"CheapHerder_product".image_url from "CheapHerder_product" where (LOWER("CheapHerder_product".product_name) LIKE LOWER('%' || query_string || '%')); 
END; $$

LANGUAGE 'plpgsql';
""")
    ]
