# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheapHerder', '0030_auto_20171206_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
